<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php80/bootstrap.php';
require_once __DIR__ . '/symfony/translation/Resources/functions.php';
require_once __DIR__ . '/symfony/deprecation-contracts/function.php';
